# Generated by Django 5.1.7 on 2025-04-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prénom', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('mail', models.CharField(default='', max_length=100)),
                ('tel', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prix', models.IntegerField()),
                ('descrip', models.CharField(default='', max_length=300)),
                ('date_ajoute', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enreg', models.DateField()),
                ('desicions', models.BooleanField(default=False)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Clients.clients')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prduits', to='Clients.produits')),
            ],
        ),
    ]
