# Generated by Django 5.1.7 on 2025-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='sexe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=models.IntegerField(max_length=100),
        ),
    ]
