# Generated by Django 5.1.7 on 2025-04-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_clients_sexe_alter_clients_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='tel',
            field=models.CharField(max_length=100),
        ),
    ]
