# Generated by Django 5.1.7 on 2025-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_clients_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='position',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='demandes',
            name='qte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
