# Generated by Django 5.1.7 on 2025-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_demandes_position_demandes_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='statut',
            field=models.CharField(default='utilisateur', max_length=100),
        ),
    ]
